import { type ClientSchema, a, defineData } from "@aws-amplify/backend";
import { postConfirmation } from "../auth/post-confirmation/resource";

// All attributes without .required() are by default Optional and will contain null value if not provided.
// We do not need to add id: a.id() to the models, since this is autogenerated by amplify for each model.
// Each model - by default, have createdAt and updatedAt field in them.
// Field like post.author -> It defines a virtual field that Amplify can resolve using author (When someone asks for post.author, amplify look for the "User" whose id === post.authorId)

const schema = a
  .schema({
    User: a
      .model({
        owner: a // Currently causing : NotAuthorized Error. (will see in future)
          .string()
          .authorization((allow) => [allow.owner()]), // (See Warning Box) : https://docs.amplify.aws/react/build-a-backend/data/customize-authz/per-user-per-owner-data-access/#add-per-userper-owner-authorization-rule
        email: a
          .string()
          .required()
          .authorization((allow) => [
            allow.authenticated().to(["read"]),
            allow.owner().to([
              "create",
              "read",
              // Diabled owner() to update/delete the email.
            ]),
          ])
          .validate((v) =>
            v.matches(
              "(?i)^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\\\.[A-Z]{2,}$", // using 4 backslashes becauses it uses java regex engine under the hood.
              "Invalid email address",
            ),
          ),
        firstName: a
          .string()
          .required()
          // .authorization((allow) => allow.authenticated().to(["read"]))
          .validate((v) =>
            v
              .minLength(2, "Must be at least 2 characters long")
              .maxLength(50, "Must be at most 50 characters long"),
          ),
        lastName: a
          .string()
          .required()
          // .authorization((allow) => allow.authenticated().to(["read"]))
          .validate((v) =>
            v
              .minLength(2, "Must be at least 2 characters long")
              .maxLength(50, "Must be at most 50 characters long"),
          ),
        // *** Non-Cognito Fields/Attributes ***
        dateOfBirth: a.date(),
        profileImage: a.string(),
        gender: a.enum(["MALE", "FEMALE", "OTHER"]),
        bio: a.string().default(""),
        // Counter Fields
        postsCount: a.integer().default(0),
        communitiesCount: a.integer().default(0),
        membershipsCount: a.integer().default(0),
        // *** Relationships ***
        posts: a.hasMany("Post", "authorId"),
        communities: a.hasMany("Community", "communityOwnerId"),
        memberships: a.hasMany("Membership", "userId"),
      })
      .authorization((allow) => [
        allow.authenticated().to(["read"]), // only single fetch allowed (not list fetch). Even then it works in each post author fetch - in post list fetch.
        allow.owner().to(["create", "read", "update"]), // by default gives full CRUD power to owner (Except "delete")
      ]),

    Post: a
      .model({
        owner: a
          .string()
          .authorization((allow) => [allow.owner().to(["read", "delete"])]), // (See Warning Box) : https://docs.amplify.aws/react/build-a-backend/data/customize-authz/per-user-per-owner-data-access/#add-per-userper-owner-authorization-rule
        title: a.string(),
        content: a.string(),
        visibility: a.enum(["PUBLIC", "COMMUNITY_ONLY"]), // Option valid only if post is posted in community - not solo.
        createdAt: a.datetime().required(), // Added to avoid typescript error in secondaryIndexes(...). Amplify will still auto-populate it, so do not edit it.
        // *** Relationships ***
        communityId: a.id(), // It's Optional
        community: a.belongsTo("Community", "communityId"),
        authorId: a.id().required(),
        author: a.belongsTo("User", "authorId"),
      })
      .authorization((allow) => [
        allow.owner(), // owners can do everything
        allow.authenticated().to(["read"]), // authenticated users can read single or multiple posts
      ])
      .secondaryIndexes((index) => [
        index("visibility")
          .sortKeys(["createdAt"])
          .queryField("listPostsByVisibility"),
        index("authorId").sortKeys(["createdAt"]).queryField("listAuthorPosts"),
        index("communityId")
          .sortKeys(["createdAt"])
          .queryField("listCommunityPosts"),
      ]),

    Community: a
      .model({
        owner: a
          .string()
          .authorization((allow) => [allow.owner().to(["read", "delete"])]), // (See Warning Box) : https://docs.amplify.aws/react/build-a-backend/data/customize-authz/per-user-per-owner-data-access/#add-per-userper-owner-authorization-rule
        name: a
          .string()
          .required()
          .authorization((allow) => [
            allow.authenticated().to(["read"]),
            allow.owner().to(["create", "delete", "read"]), // by default gives full CRUD power to owner (Except "update")
          ]),
        description: a.string().required(),
        visibility: a.enum(["PUBLIC", "PRIVATE"]), // default()/required() can't be applied here for now. (https://github.com/aws-amplify/amplify-data/issues/452)
        createdAt: a.datetime().required(), // Added to avoid typescript error in secondaryIndexes(...). Amplify will still auto-populate it, so do not edit it.
        // Counter Fields
        postsCount: a.integer().default(0),
        membershipsCount: a.integer().default(0),
        // *** Relationships ***
        communityOwnerId: a.id().required(),
        communityOwner: a.belongsTo("User", "communityOwnerId"),

        posts: a.hasMany("Post", "communityId"),
        memberships: a.hasMany("Membership", "communityId"),
      })
      .authorization((allow) => [
        allow.authenticated().to(["read", "update"]),
        allow.owner(), // by default gives full CRUD for owner
      ])
      .secondaryIndexes((index) => [
        index("visibility")
          .sortKeys(["createdAt"])
          .queryField("listCommunitiesByVisibility"),
      ]),

    Membership: a
      .model({
        owner: a
          .string()
          .authorization((allow) => [allow.owner().to(["read", "delete"])]), // (See Warning Box) : https://docs.amplify.aws/react/build-a-backend/data/customize-authz/per-user-per-owner-data-access/#add-per-userper-owner-authorization-rule
        role: a.enum(["VIEWER", "WRITER", "ADMIN"]),
        // status: a.enum(["ACTIVE", "PENDING", "REJECTED", "REMOVED"]), // If admin removes the user, the status = "REMOVED", if user leaves then this object gets deleted.
        // ### Relationships ###
        communityId: a.id().required(),
        community: a.belongsTo("Community", "communityId"),
        userId: a.id().required(),
        user: a.belongsTo("User", "userId"),
      })
      .authorization((allow) => [
        allow.authenticated().to(["read"]),
        allow.owner(), // by default gives full CRUD for owner
      ]),
  })
  .authorization((allow) => [allow.resource(postConfirmation)]);

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "userPool", // Only signed-in users can call the API, API calls are signed with a JWT access token, proving “who the user is”. (Requests without a valid signed-in user will be rejected)
    // defaultAuthorizationMode: "identityPool", // any user (authenticated or unauthenticated) can access the model. (but allow.owner() will not work with this.)
  },
});
